/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author Ian
 */
public class ActivityCreation extends javax.swing.JPanel {

    /**
     * Creates new form ActivityCreation
     */
    public ActivityCreation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create_activity_pane = new javax.swing.JTabbedPane();
        create_activity_tab = new javax.swing.JPanel();
        activity_name_label = new javax.swing.JLabel();
        activity_type_label = new javax.swing.JLabel();
        activity_desc_label = new javax.swing.JLabel();
        activity_lang_label = new javax.swing.JLabel();
        activity_due_date_1_label = new javax.swing.JLabel();
        activity_name_field = new javax.swing.JTextField();
        activity_type_field = new javax.swing.JTextField();
        activity_desc_field = new javax.swing.JTextField();
        activity_lang_field = new javax.swing.JTextField();
        activity_due_date_1_time = new javax.swing.JTextField();
        activity_due_date_1_field = new javax.swing.JFormattedTextField();
        activity_individual_checkbox = new javax.swing.JRadioButton();
        activity_group_checkbox = new javax.swing.JRadioButton();
        additional_due_date_button = new javax.swing.JButton();
        activity_solution_button = new javax.swing.JButton();
        activity_test_inout_button = new javax.swing.JButton();
        activity_test_outin_field = new javax.swing.JTextField();
        activity_submit_button = new javax.swing.JButton();
        activity_solution_field = new javax.swing.JTextField();
        activity_testcomment_label = new javax.swing.JLabel();
        activity_test_number_label = new javax.swing.JLabel();
        activity_test_number_field = new javax.swing.JTextField();
        activity_student_submissionpath_button = new javax.swing.JButton();
        activity_student_submissionpath_field = new javax.swing.JTextField();
        activity_reset_button = new javax.swing.JButton();
        activity_rubric_tab = new javax.swing.JPanel();
        rubric_additional_row_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rubric_table = new javax.swing.JTable();
        rubric_submit_button = new javax.swing.JButton();

        activity_name_label.setText("Activity Name");

        activity_type_label.setText("Type");

        activity_desc_label.setText("Description");

        activity_lang_label.setText("Language");

        activity_due_date_1_label.setText("Due Date 1");

        activity_type_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activity_type_fieldActionPerformed(evt);
            }
        });

        activity_due_date_1_time.setText("23:59");

        activity_individual_checkbox.setText("Individual");

        activity_group_checkbox.setText("Group");

        additional_due_date_button.setText("Additional Due Date");
        additional_due_date_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additional_due_date_buttonActionPerformed(evt);
            }
        });

        activity_solution_button.setText("Attach Solution");
        activity_solution_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activity_solution_buttonActionPerformed(evt);
            }
        });

        activity_test_inout_button.setText("Test output/inputs**");
        activity_test_inout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activity_test_inout_buttonActionPerformed(evt);
            }
        });

        activity_submit_button.setText("Submit");
        activity_submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activity_submit_buttonActionPerformed(evt);
            }
        });

        activity_solution_field.setText("File Location...");
        activity_solution_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activity_solution_fieldActionPerformed(evt);
            }
        });

        activity_testcomment_label.setText("** Leave empty if Activity Type is not Programming!");
        activity_testcomment_label.setToolTipText("");

        activity_test_number_label.setText("Number of Programming Tests");

        activity_test_number_field.setText("0");
        activity_test_number_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activity_test_number_fieldActionPerformed(evt);
            }
        });

        activity_student_submissionpath_button.setText("Student Submission Path");
        activity_student_submissionpath_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activity_student_submissionpath_buttonActionPerformed(evt);
            }
        });

        activity_reset_button.setText("Reset");
        activity_reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activity_reset_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout create_activity_tabLayout = new javax.swing.GroupLayout(create_activity_tab);
        create_activity_tab.setLayout(create_activity_tabLayout);
        create_activity_tabLayout.setHorizontalGroup(
            create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_activity_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, create_activity_tabLayout.createSequentialGroup()
                        .addComponent(activity_reset_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activity_submit_button))
                    .addGroup(create_activity_tabLayout.createSequentialGroup()
                        .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(create_activity_tabLayout.createSequentialGroup()
                                .addComponent(activity_individual_checkbox)
                                .addGap(10, 10, 10)
                                .addComponent(activity_group_checkbox))
                            .addGroup(create_activity_tabLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(create_activity_tabLayout.createSequentialGroup()
                                        .addComponent(activity_due_date_1_label)
                                        .addGap(12, 12, 12)
                                        .addComponent(activity_due_date_1_field, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(activity_due_date_1_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(additional_due_date_button))
                                    .addGroup(create_activity_tabLayout.createSequentialGroup()
                                        .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(activity_name_label)
                                            .addComponent(activity_type_label)
                                            .addComponent(activity_desc_label)
                                            .addComponent(activity_lang_label))
                                        .addGap(50, 50, 50)
                                        .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(activity_lang_field, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                            .addComponent(activity_desc_field)
                                            .addComponent(activity_type_field)
                                            .addComponent(activity_name_field)))
                                    .addGroup(create_activity_tabLayout.createSequentialGroup()
                                        .addComponent(activity_test_number_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(activity_test_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(create_activity_tabLayout.createSequentialGroup()
                                .addComponent(activity_student_submissionpath_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activity_student_submissionpath_field))
                            .addGroup(create_activity_tabLayout.createSequentialGroup()
                                .addComponent(activity_solution_button)
                                .addGap(18, 18, 18)
                                .addComponent(activity_solution_field, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(activity_testcomment_label)
                            .addGroup(create_activity_tabLayout.createSequentialGroup()
                                .addComponent(activity_test_inout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(activity_test_outin_field)))
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        create_activity_tabLayout.setVerticalGroup(
            create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_activity_tabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_name_label)
                    .addComponent(activity_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_type_label)
                    .addComponent(activity_type_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_desc_label)
                    .addComponent(activity_desc_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_lang_label)
                    .addComponent(activity_lang_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_individual_checkbox)
                    .addComponent(activity_group_checkbox))
                .addGap(8, 8, 8)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_due_date_1_label)
                    .addComponent(activity_due_date_1_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activity_due_date_1_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additional_due_date_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_test_number_label, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(activity_test_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_test_inout_button)
                    .addComponent(activity_test_outin_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activity_testcomment_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_student_submissionpath_button)
                    .addComponent(activity_student_submissionpath_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_solution_button)
                    .addComponent(activity_solution_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(create_activity_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activity_submit_button)
                    .addComponent(activity_reset_button))
                .addContainerGap())
        );

        create_activity_pane.addTab("Activity", create_activity_tab);

        rubric_additional_row_button.setText("Additional Row");
        rubric_additional_row_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rubric_additional_row_buttonActionPerformed(evt);
            }
        });

        rubric_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Description", "Max Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rubric_table);

        rubric_submit_button.setText("Submit");

        javax.swing.GroupLayout activity_rubric_tabLayout = new javax.swing.GroupLayout(activity_rubric_tab);
        activity_rubric_tab.setLayout(activity_rubric_tabLayout);
        activity_rubric_tabLayout.setHorizontalGroup(
            activity_rubric_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activity_rubric_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activity_rubric_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rubric_additional_row_button)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activity_rubric_tabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rubric_submit_button)
                .addContainerGap())
        );
        activity_rubric_tabLayout.setVerticalGroup(
            activity_rubric_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activity_rubric_tabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(rubric_additional_row_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(rubric_submit_button)
                .addContainerGap())
        );

        create_activity_pane.addTab("Rubric", activity_rubric_tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(create_activity_pane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(create_activity_pane)
        );

        create_activity_pane.getAccessibleContext().setAccessibleName("create_activity_pane");
    }// </editor-fold>//GEN-END:initComponents

    private void activity_solution_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activity_solution_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activity_solution_buttonActionPerformed

    private void activity_test_inout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activity_test_inout_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activity_test_inout_buttonActionPerformed

    private void activity_solution_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activity_solution_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activity_solution_fieldActionPerformed

    private void activity_type_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activity_type_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activity_type_fieldActionPerformed

    private void rubric_additional_row_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rubric_additional_row_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rubric_additional_row_buttonActionPerformed

    private void activity_test_number_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activity_test_number_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activity_test_number_fieldActionPerformed

    private void activity_student_submissionpath_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activity_student_submissionpath_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activity_student_submissionpath_buttonActionPerformed

    private void additional_due_date_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additional_due_date_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_additional_due_date_buttonActionPerformed

    private void activity_reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activity_reset_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activity_reset_buttonActionPerformed

    private void activity_submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activity_submit_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activity_submit_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activity_desc_field;
    private javax.swing.JLabel activity_desc_label;
    private javax.swing.JFormattedTextField activity_due_date_1_field;
    private javax.swing.JLabel activity_due_date_1_label;
    private javax.swing.JTextField activity_due_date_1_time;
    private javax.swing.JRadioButton activity_group_checkbox;
    private javax.swing.JRadioButton activity_individual_checkbox;
    private javax.swing.JTextField activity_lang_field;
    private javax.swing.JLabel activity_lang_label;
    private javax.swing.JTextField activity_name_field;
    private javax.swing.JLabel activity_name_label;
    private javax.swing.JButton activity_reset_button;
    private javax.swing.JPanel activity_rubric_tab;
    private javax.swing.JButton activity_solution_button;
    private javax.swing.JTextField activity_solution_field;
    private javax.swing.JButton activity_student_submissionpath_button;
    private javax.swing.JTextField activity_student_submissionpath_field;
    private javax.swing.JButton activity_submit_button;
    private javax.swing.JButton activity_test_inout_button;
    private javax.swing.JTextField activity_test_number_field;
    private javax.swing.JLabel activity_test_number_label;
    private javax.swing.JTextField activity_test_outin_field;
    private javax.swing.JLabel activity_testcomment_label;
    private javax.swing.JTextField activity_type_field;
    private javax.swing.JLabel activity_type_label;
    private javax.swing.JButton additional_due_date_button;
    private javax.swing.JTabbedPane create_activity_pane;
    private javax.swing.JPanel create_activity_tab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rubric_additional_row_button;
    private javax.swing.JButton rubric_submit_button;
    private javax.swing.JTable rubric_table;
    // End of variables declaration//GEN-END:variables
}
