/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import database.AccountAccess;
import gui.types.*;
import gui.utils.GUIUtils;

import java.awt.event.*;
import javax.swing.*;
import types.*;

/**
 *
 * @author Markus
 */
public class CreateAccount extends MSPanel {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
	super("Account Management", CANT_NAV);

        initComponents();
        
        existing_account_dropdown
		.setModel(new javax.swing.DefaultComboBoxModel(
				database.AccountAccess.accessAccountList()));
        
        
        if (existing_account_dropdown.getItemCount() == 0)
        {
        	modify_existing_checkbox.setEnabled(false);
            existing_account_dropdown.setEnabled(false);
            delete_account_button.setEnabled(false);
            ClearFields();
            System.out.println("ERROR NOTHING IN DROPDOWN");
        }
        
        //Manually added listener for combobox changes
        existing_account_dropdown.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
		
                existing_account_dropdown = (JComboBox) e.getSource();
                fillFieldsFromSelection();
            }
        });
        
       }
    
    private void ClearFields()
    {
        first_name_field.setText("");
        last_name_field.setText("");
        id_field.setText("");
        username_field.setText("");
        password_field.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        account_creation_header = new javax.swing.JPanel();
        first_name_field = new javax.swing.JTextField();
        last_name_field = new javax.swing.JTextField();
        account_type_dropdown = new javax.swing.JComboBox();
        username_field = new javax.swing.JTextField();
        password_generate_button = new javax.swing.JButton();
        first_name_label = new javax.swing.JLabel();
        last_name_label = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        account_type_label = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        modify_existing_checkbox = new javax.swing.JCheckBox();
        existing_account_dropdown = new javax.swing.JComboBox();
        existing_account_separator = new javax.swing.JSeparator();
        ok_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        password_field = new javax.swing.JTextField();
        id_field = new javax.swing.JFormattedTextField();
        delete_account_button = new javax.swing.JButton();
        block_account_checkbox = new javax.swing.JCheckBox();

        account_creation_header.setBorder(javax.swing.BorderFactory.createTitledBorder("Create/Modify an Account:"));
        account_creation_header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        account_creation_header.setName(""); // NOI18N

        first_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_name_fieldActionPerformed(evt);
            }
        });

        account_type_dropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "System Admin", "Administrator", "Assistant Admin", "Instructor", "TA" }));
        account_type_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account_type_dropdownActionPerformed(evt);
            }
        });

        password_generate_button.setText("Generate");
        password_generate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_generate_buttonActionPerformed(evt);
            }
        });

        first_name_label.setText("First Name");

        last_name_label.setText("Last Name");

        id_label.setText("Employee ID");

        account_type_label.setText("Account Type");

        username_label.setText("Username");

        password_label.setText("Password");

        modify_existing_checkbox.setText("Modify Existing Account");
        modify_existing_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_existing_checkboxActionPerformed(evt);
            }
        });

        existing_account_dropdown.setEnabled(false);

        existing_account_separator.setForeground(new java.awt.Color(0, 0, 0));

        ok_button.setText("OK");
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        id_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#######################"))));

        delete_account_button.setText("Delete Account");
        delete_account_button.setEnabled(false);
        delete_account_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_account_buttonActionPerformed(evt);
            }
        });

        block_account_checkbox.setText("Block Account");
        block_account_checkbox.setEnabled(false);

        javax.swing.GroupLayout account_creation_headerLayout = new javax.swing.GroupLayout(account_creation_header);
        account_creation_header.setLayout(account_creation_headerLayout);
        account_creation_headerLayout.setHorizontalGroup(
            account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, account_creation_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(existing_account_separator)
                .addContainerGap())
            .addGroup(account_creation_headerLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, account_creation_headerLayout.createSequentialGroup()
                        .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(account_creation_headerLayout.createSequentialGroup()
                                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(account_creation_headerLayout.createSequentialGroup()
                                        .addComponent(password_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(password_generate_button))
                                    .addGroup(account_creation_headerLayout.createSequentialGroup()
                                        .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(last_name_label)
                                            .addComponent(account_type_label)
                                            .addComponent(username_label)
                                            .addComponent(first_name_label))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(account_creation_headerLayout.createSequentialGroup()
                                .addComponent(id_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(password_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(first_name_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(last_name_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(account_type_dropdown, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(username_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_field, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(account_creation_headerLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancel_button))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, account_creation_headerLayout.createSequentialGroup()
                        .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modify_existing_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(block_account_checkbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(existing_account_dropdown, 0, 120, Short.MAX_VALUE)
                            .addComponent(delete_account_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)))
                .addGap(18, 18, 18))
        );
        account_creation_headerLayout.setVerticalGroup(
            account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, account_creation_headerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modify_existing_checkbox)
                    .addComponent(existing_account_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete_account_button)
                    .addComponent(block_account_checkbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(existing_account_separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_label)
                    .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(account_type_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(account_type_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_generate_button)
                    .addComponent(password_label)
                    .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(account_creation_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_button)
                    .addComponent(cancel_button))
                .addGap(4, 4, 4))
        );

        ok_button.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(account_creation_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(account_creation_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void first_name_fieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_first_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_name_fieldActionPerformed

    private void account_type_dropdownActionPerformed(ActionEvent evt) {//GEN-FIRST:event_account_type_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_account_type_dropdownActionPerformed

    private void password_generate_buttonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_password_generate_buttonActionPerformed
        password_field.setText(GUIUtils.generatePassword());
    }//GEN-LAST:event_password_generate_buttonActionPerformed

    private void modify_existing_checkboxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_modify_existing_checkboxActionPerformed
        if (modify_existing_checkbox.isSelected())
        {
        existing_account_dropdown.setEnabled(true);
        delete_account_button.setEnabled(true);
        block_account_checkbox.setEnabled(true);
        
        //Populate fields with information from user
        fillFieldsFromSelection();
        }
        
        else
        {
        block_account_checkbox.setSelected(false);
        block_account_checkbox.setEnabled(false);
        existing_account_dropdown.setEnabled(false);     
        delete_account_button.setEnabled(false);
        ClearFields();
        }
    }//GEN-LAST:event_modify_existing_checkboxActionPerformed

    private void fillFieldsFromSelection()
    {
    	if (existing_account_dropdown.getSelectedIndex() == -1)
            System.out.println("No valid index selected, nothing to print.");
        
        else {
        
        String account_username = (String) existing_account_dropdown.getSelectedItem();
        Account fill_acct = AccountAccess.constructAccountObject(account_username);
        
        first_name_field.setText(fill_acct.getFirstName());
        last_name_field.setText(fill_acct.getLastName());
        id_field.setValue(fill_acct.getEmpID());
        account_type_dropdown.setSelectedIndex(fill_acct.getAccountTypeAsInt()-1);
        username_field.setText(fill_acct.getUsername());
        password_field.setText(fill_acct.getPassword()); 
        block_account_checkbox.setSelected(fill_acct.isBlocked());
        }
     }
    
    private void ok_buttonActionPerformed(ActionEvent evt) {// GEN-FIRST:event_ok_buttonActionPerformed
	String first = first_name_field.getText();
	String last = last_name_field.getText();
	int id = Integer.parseInt(id_field.getText());
	String username = username_field.getText();
	String pass = password_field.getText();
	boolean block_value = block_account_checkbox.isSelected();
	Account creation;
	String account_select = account_type_dropdown.getSelectedItem()
	    .toString();

	if (account_select.equalsIgnoreCase("System Admin"))
	    creation = new SystemAdmin(first, last, id, username, pass);

	else if (account_select.equalsIgnoreCase("Administrator"))
	    creation = new AcademicAdmin(first, last, id, username, pass);

	else if (account_select.equalsIgnoreCase("Assistant Admin"))
	    creation = new AssistantAdmin(first, last, id, username, pass);

	else if (account_select.equalsIgnoreCase("Instructor"))
	    creation = new Instructor(first, last, id, username, pass);

	else if (account_select.equalsIgnoreCase("TA"))
	    creation = new TATM(first, last, id, username, pass);

	else { // Incorrect account type, this should never happen
	    creation = null;
	    System.out.println("Is it Christmas right now? Because you have an"
					+ " error message to unwrap.");
	}

	if (modify_existing_checkbox.isSelected()) {
	    creation.setBlocked(block_value);
	    AccountAccess.modifyAccount(existing_account_dropdown
					.getSelectedItem().toString(), creation);
	    if (!block_value)
		AccountAccess.successfulLogin(username);
	    System.out.println("Account " + username_field.getText()
			       + " modified.");
	} else {
	    System.out.println("Creating " + account_select + " type account.");
	    AccountAccess.createAccount(creation);
	    JOptionPane.showMessageDialog(this, "Account Created: "
					  + username_field.getText());
	}

	setOkToNav();
	GUIUtils.getMasterFrame(this).goBack();
    }//GEN-LAST:event_ok_buttonActionPerformed
    
    private void cancel_buttonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
	GUIUtils.getMasterFrame(this).goBack();
    }//GEN-LAST:event_cancel_buttonActionPerformed

	private void delete_account_buttonActionPerformed(ActionEvent evt) {
		String account = existing_account_dropdown.getSelectedItem().toString();

		int confirm = JOptionPane.showConfirmDialog(this, "Delete account \""
				+ username_field.getText() + "\"?", "",
				JOptionPane.YES_NO_OPTION);
		if (confirm == 0) {
			AccountAccess.deleteAccount(account);
			ClearFields();
			existing_account_dropdown.removeAllItems();
			existing_account_dropdown
					.setModel(new javax.swing.DefaultComboBoxModel(
							database.AccountAccess.accessAccountList()));
			existing_account_dropdown.setSelectedIndex(-1);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel account_creation_header;
    private javax.swing.JComboBox account_type_dropdown;
    private javax.swing.JLabel account_type_label;
    private javax.swing.JCheckBox block_account_checkbox;
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton delete_account_button;
    private javax.swing.JComboBox existing_account_dropdown;
    private javax.swing.JSeparator existing_account_separator;
    private javax.swing.JTextField first_name_field;
    private javax.swing.JLabel first_name_label;
    private javax.swing.JFormattedTextField id_field;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField last_name_field;
    private javax.swing.JLabel last_name_label;
    private javax.swing.JCheckBox modify_existing_checkbox;
    private javax.swing.JButton ok_button;
    private javax.swing.JTextField password_field;
    private javax.swing.JButton password_generate_button;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
