/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author Pun
 */
public class CreateCoursePg extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    public CreateCoursePg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_panel = new javax.swing.JPanel();
        role_label = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        create_course_panel = new javax.swing.JPanel();
        course_name_label = new javax.swing.JLabel();
        course_id_label = new javax.swing.JLabel();
        instructor_name_label = new javax.swing.JLabel();
        instructor_id_label = new javax.swing.JLabel();
        ta_name_label = new javax.swing.JLabel();
        ta_id_label = new javax.swing.JLabel();
        course_start_label = new javax.swing.JLabel();
        stud_list_label = new javax.swing.JLabel();
        course_end_label = new javax.swing.JLabel();
        course_name_field = new javax.swing.JTextField();
        course_id_field = new javax.swing.JTextField();
        instructor_name_field = new javax.swing.JTextField();
        instructor_id_field = new javax.swing.JTextField();
        ta_name_field = new javax.swing.JTextField();
        ta_id_field = new javax.swing.JTextField();
        course_start_formatfield = new javax.swing.JFormattedTextField();
        course_end_formatfield = new javax.swing.JFormattedTextField();
        stud_list_file_location_field = new javax.swing.JTextField();
        choose_file_student_list_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        submit_course = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MarkShark - Create A Page");
        setResizable(false);

        role_label.setText("Role: Assistant Admin.");

        logout_button.setText("Log Out");

        back_button.setText("Back");

        create_course_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create A Course"));

        course_name_label.setText("Course Name");

        course_id_label.setText("Course ID");

        instructor_name_label.setText("Instructor Name");

        instructor_id_label.setText("Instructor ID");

        ta_name_label.setText("TA/Marker Name");

        ta_id_label.setText("TA/Marker ID");

        course_start_label.setText("Course Start Date");

        stud_list_label.setText("Student List (.csv)");

        course_end_label.setText("Course End Date");

        course_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_name_fieldActionPerformed(evt);
            }
        });

        instructor_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructor_name_fieldActionPerformed(evt);
            }
        });

        course_start_formatfield.setText("DD/MM/YY");

        course_end_formatfield.setText("DD/MM/YY");
        course_end_formatfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_end_formatfieldActionPerformed(evt);
            }
        });

        stud_list_file_location_field.setText("File Location...");

        choose_file_student_list_button.setText("Choose File");

        javax.swing.GroupLayout create_course_panelLayout = new javax.swing.GroupLayout(create_course_panel);
        create_course_panel.setLayout(create_course_panelLayout);
        create_course_panelLayout.setHorizontalGroup(
            create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_course_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(create_course_panelLayout.createSequentialGroup()
                        .addComponent(stud_list_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stud_list_file_location_field, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(choose_file_student_list_button))
                    .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, create_course_panelLayout.createSequentialGroup()
                            .addComponent(course_name_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(course_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, create_course_panelLayout.createSequentialGroup()
                            .addComponent(instructor_name_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instructor_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(create_course_panelLayout.createSequentialGroup()
                            .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ta_id_label)
                                .addComponent(course_id_label))
                            .addGap(133, 133, 133)
                            .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(course_id_field)
                                .addComponent(ta_id_field)))
                        .addGroup(create_course_panelLayout.createSequentialGroup()
                            .addComponent(course_start_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(course_start_formatfield, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(course_end_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(course_end_formatfield, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(create_course_panelLayout.createSequentialGroup()
                            .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ta_name_label)
                                .addComponent(instructor_id_label))
                            .addGap(117, 117, 117)
                            .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(instructor_id_field)
                                .addComponent(ta_name_field)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        create_course_panelLayout.setVerticalGroup(
            create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_course_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_id_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructor_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructor_name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructor_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructor_id_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ta_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ta_name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ta_id_label)
                    .addComponent(ta_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_start_label)
                    .addComponent(course_start_formatfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_end_label)
                    .addComponent(course_end_formatfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(create_course_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stud_list_label)
                    .addComponent(stud_list_file_location_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choose_file_student_list_button))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        cancel_button.setText("Submit");

        submit_course.setText("Cancel");

        javax.swing.GroupLayout top_panelLayout = new javax.swing.GroupLayout(top_panel);
        top_panel.setLayout(top_panelLayout);
        top_panelLayout.setHorizontalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addGroup(top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_panelLayout.createSequentialGroup()
                        .addGroup(top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(top_panelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(create_course_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(top_panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(submit_course)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancel_button)))
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addGroup(top_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(top_panelLayout.createSequentialGroup()
                                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 490, Short.MAX_VALUE)
                                .addComponent(logout_button))
                            .addGroup(top_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(role_label)))))
                .addContainerGap())
        );
        top_panelLayout.setVerticalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(role_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout_button)
                    .addComponent(back_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create_course_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_button)
                    .addComponent(submit_course))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(655, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void course_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_name_fieldActionPerformed

    private void course_end_formatfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_end_formatfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_end_formatfieldActionPerformed

    private void instructor_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructor_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructor_name_fieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton choose_file_student_list_button;
    private javax.swing.JFormattedTextField course_end_formatfield;
    private javax.swing.JLabel course_end_label;
    private javax.swing.JTextField course_id_field;
    private javax.swing.JLabel course_id_label;
    private javax.swing.JTextField course_name_field;
    private javax.swing.JLabel course_name_label;
    private javax.swing.JFormattedTextField course_start_formatfield;
    private javax.swing.JLabel course_start_label;
    private javax.swing.JPanel create_course_panel;
    private javax.swing.JTextField instructor_id_field;
    private javax.swing.JLabel instructor_id_label;
    private javax.swing.JTextField instructor_name_field;
    private javax.swing.JLabel instructor_name_label;
    private javax.swing.JButton logout_button;
    private javax.swing.JLabel role_label;
    private javax.swing.JTextField stud_list_file_location_field;
    private javax.swing.JLabel stud_list_label;
    private javax.swing.JButton submit_course;
    private javax.swing.JTextField ta_id_field;
    private javax.swing.JLabel ta_id_label;
    private javax.swing.JTextField ta_name_field;
    private javax.swing.JLabel ta_name_label;
    private javax.swing.JPanel top_panel;
    // End of variables declaration//GEN-END:variables
}
