/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import gui.utils.*;
import gui.types.*;
import javax.swing.*;
import java.awt.event.*;
import types.*;

/**
 *
 * @author colin
 */
public class DatabaseManagement extends MSPanel {
    private SystemAdmin a;

    /**
     * Creates new form LandingPageSysAdmin
     */
    public DatabaseManagement(SystemAdmin a) {
	super("System Administrator");
        initComponents();
        
        previous_backup_dropdown.setEnabled(false);
        restore_button.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tasks_panel = new javax.swing.JPanel();
        backup_button = new javax.swing.JButton();
        previous_backup_toggle = new javax.swing.JRadioButton();
        previous_backup_dropdown = new javax.swing.JComboBox();
        backup_progressbar = new javax.swing.JProgressBar();
        restore_button = new javax.swing.JButton();
        backup_separator = new javax.swing.JSeparator();

        tasks_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tasks"));

        backup_button.setText("Backup Database Manually");

        previous_backup_toggle.setText("Restore from previous Backup:");
        previous_backup_toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previous_backup_toggleActionPerformed(evt);
            }
        });

        previous_backup_dropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        restore_button.setText("Restore from Selected Backup");

        javax.swing.GroupLayout tasks_panelLayout = new javax.swing.GroupLayout(tasks_panel);
        tasks_panel.setLayout(tasks_panelLayout);
        tasks_panelLayout.setHorizontalGroup(
            tasks_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasks_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tasks_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backup_separator)
                    .addGroup(tasks_panelLayout.createSequentialGroup()
                        .addComponent(backup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(backup_progressbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tasks_panelLayout.createSequentialGroup()
                        .addComponent(previous_backup_toggle)
                        .addGap(42, 42, 42)
                        .addGroup(tasks_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restore_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(previous_backup_dropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        tasks_panelLayout.setVerticalGroup(
            tasks_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tasks_panelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(tasks_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backup_button)
                    .addComponent(backup_progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(backup_separator, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tasks_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previous_backup_toggle)
                    .addComponent(previous_backup_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restore_button)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tasks_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tasks_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void previous_backup_toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previous_backup_toggleActionPerformed
        if (previous_backup_toggle.isSelected()) {
            //disables
            backup_button.setEnabled(false);
            backup_progressbar.setEnabled(false);
            
            //enables
            previous_backup_dropdown.setEnabled(true);
            restore_button.setEnabled(true);
        }
        else {
            //disables
            previous_backup_dropdown.setEnabled(false);
            restore_button.setEnabled(false);
            
            //enables
            backup_button.setEnabled(true);
            backup_progressbar.setEnabled(true);
        }
    }//GEN-LAST:event_previous_backup_toggleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backup_button;
    private javax.swing.JProgressBar backup_progressbar;
    private javax.swing.JSeparator backup_separator;
    private javax.swing.JComboBox previous_backup_dropdown;
    private javax.swing.JRadioButton previous_backup_toggle;
    private javax.swing.JButton restore_button;
    private javax.swing.JPanel tasks_panel;
    // End of variables declaration//GEN-END:variables
}
