/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import gui.utils.*;
import gui.types.*;
import types.*;

/**
 *
 * @author Jordan
 */
public class LandingPageAssistAdmin extends MSPanel {
    private AssistantAdmin a;

    /**
     * Creates new form LandingPageAssistAdmin1
     */
    public LandingPageAssistAdmin(AssistantAdmin a) {
	super("Assistant Academic Administrator");
	this.a = a;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        course_selection_header = new javax.swing.JPanel();
        course_management_button = new javax.swing.JButton();

        course_selection_header.setBorder(javax.swing.BorderFactory.createTitledBorder("Tasks"));
        course_selection_header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        course_selection_header.setName(""); // NOI18N

        course_management_button.setText("Course Management");
        course_management_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_management_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout course_selection_headerLayout = new javax.swing.GroupLayout(course_selection_header);
        course_selection_header.setLayout(course_selection_headerLayout);
        course_selection_headerLayout.setHorizontalGroup(
            course_selection_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, course_selection_headerLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(course_management_button)
                .addGap(169, 169, 169))
        );
        course_selection_headerLayout.setVerticalGroup(
            course_selection_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(course_selection_headerLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(course_management_button)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(course_selection_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(course_selection_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void course_management_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_management_buttonActionPerformed
        GUIUtils.getMasterFrame(this).movePage(new CourseManagement(a));
    }//GEN-LAST:event_course_management_buttonActionPerformed

    private static final int MODIFY_COURSE = 1;
    private static final int DELETE_COURSE = 2;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton course_management_button;
    private javax.swing.JPanel course_selection_header;
    // End of variables declaration//GEN-END:variables
}
