/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import gui.utils.*;
import gui.types.*;
import javax.swing.*;
import java.awt.event.*;
import types.*;

/**
 *
 * @author colin
 */
public class LandingPageSysAdmin extends MSPanel {
    private SystemAdmin a;

    /**
     * Creates new form LandingPageSysAdmin
     */
    public LandingPageSysAdmin(SystemAdmin a) {
	super("System Administrator");
	this.a = a;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tasks_panel = new JPanel();
        manage_database_button = new JButton();
        manage_accounts_button = new JButton();
        manage_log_button = new JButton();

        tasks_panel.setBorder(BorderFactory.createTitledBorder("Tasks"));

        manage_database_button.setText("Manage Database");
        manage_database_button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                manage_database_buttonActionPerformed(evt);
            }
        });

        manage_accounts_button.setText("Manage Accounts");
        manage_accounts_button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                manage_accounts_buttonActionPerformed(evt);
            }
        });

        manage_log_button.setText("Manage Logs");
        manage_log_button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                manage_log_buttonActionPerformed(evt);
            }
        });

        GroupLayout tasks_panelLayout = new GroupLayout(tasks_panel);
        tasks_panel.setLayout(tasks_panelLayout);
        tasks_panelLayout.setHorizontalGroup(
            tasks_panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tasks_panelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(tasks_panelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(manage_accounts_button, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage_log_button, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage_database_button, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        tasks_panelLayout.setVerticalGroup(
            tasks_panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tasks_panelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(manage_database_button)
                .addGap(34, 34, 34)
                .addComponent(manage_accounts_button)
                .addGap(32, 32, 32)
                .addComponent(manage_log_button)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tasks_panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tasks_panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manage_database_buttonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_manage_database_buttonActionPerformed
	 GUIUtils.getMasterFrame(this).movePage(new DatabaseManagement(a));
    }//GEN-LAST:event_manage_database_buttonActionPerformed

    private void manage_accounts_buttonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_manage_accounts_buttonActionPerformed
        GUIUtils.getMasterFrame(this).movePage(new CreateAccount());
    }//GEN-LAST:event_manage_accounts_buttonActionPerformed

    private void manage_log_buttonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_manage_log_buttonActionPerformed
        GUIUtils.getMasterFrame(this).movePage(new LogManagement());
    }//GEN-LAST:event_manage_log_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton manage_accounts_button;
    private JButton manage_database_button;
    private JButton manage_log_button;
    private JPanel tasks_panel;
    // End of variables declaration//GEN-END:variables
}
